"""Verify that the built wheel contains the deployable SaaS boundary."""

from __future__ import annotations

import argparse
import sys
import zipfile
from collections.abc import Collection
from pathlib import Path

REQUIRED_WHEEL_PATHS = (
    "saas/application.py",
    "saas/openapi-v1.json",
    "saas/scim_schema_catalog.py",
    "saas/approval_scheduler_worker.py",
    "saas/billing_metering_transport.py",
    "saas/acceptance/p0-p6-evidence.json",
    "saas/acceptance/p0-adr-approval-contract-ci-31276530223.json",
    "saas/acceptance/p0-adr-approval-evidence-ci-33468247922.json",
    "saas/acceptance/p0-n1-security-compat-image-candidate-ci-33020428815.json",
    "saas/acceptance/pc1-platform-security-ci-31187073403.json",
    "saas/acceptance/pc1-platform-security-image-candidate-ci-31187141816.json",
    "saas/acceptance/pc2-p6-lifecycle-period-close-ci-31201598950.json",
    "saas/acceptance/pc2-p6-lifecycle-period-close-image-candidate-ci-31202057865.json",
    "saas/acceptance/pc2-identity-conflict-p6-restore-ci-31211571929.json",
    "saas/acceptance/pc2-identity-conflict-p6-restore-image-candidate-ci-31211571817.json",
    "saas/acceptance/pc3-governed-access-ci-31223549606.json",
    "saas/acceptance/pc3-governed-access-image-candidate-ci-31223584072.json",
    "saas/acceptance/pc4-platform-console-ci-31230374740.json",
    "saas/acceptance/pc4-platform-console-image-candidate-ci-31230374738.json",
    "saas/acceptance/pc5-enterprise-scim-ci-31233595734.json",
    "saas/acceptance/pc5-enterprise-scim-image-candidate-ci-31233595699.json",
    "saas/acceptance/pc5-scim-credential-lifecycle-ci-31239595356.json",
    "saas/acceptance/pc5-scim-credential-lifecycle-image-candidate-ci-31239616246.json",
    "saas/acceptance/pc5-scim-list-filter-ci-31242675519.json",
    "saas/acceptance/pc5-scim-list-filter-image-candidate-ci-31242683505.json",
    "saas/acceptance/pc5-scim-resource-lifecycle-ci-31246087422.json",
    "saas/acceptance/pc5-scim-resource-lifecycle-image-candidate-ci-31246057815.json",
    "saas/acceptance/pc5-scim-compound-filter-sort-ci-31249990283.json",
    "saas/acceptance/pc5-scim-compound-filter-sort-image-candidate-ci-31250015114.json",
    "saas/acceptance/pc5-scim-bulk-ci-31254116952.json",
    "saas/acceptance/pc5-scim-bulk-image-candidate-ci-31254116960.json",
    "saas/acceptance/pc5-scim-credential-overlap-ci-31257782799.json",
    "saas/acceptance/pc5-scim-credential-overlap-image-candidate-ci-31257782706.json",
    "saas/acceptance/pc5-scim-comparison-value-path-ci-31271156219.json",
    "saas/acceptance/pc5-scim-comparison-value-path-image-candidate-ci-31271156205.json",
    "saas/acceptance/p1-context-shell-ci-30890178928.json",
    "saas/acceptance/p1-oidc-ci-30887476782.json",
    "saas/acceptance/p2-ci-30883002639.json",
    "saas/acceptance/p2-upstream-sync-ci-30883850613.json",
    "saas/acceptance/p2-upstream-sync-ci-30884588165.json",
    "saas/acceptance/p3-ci-30895599094.json",
    "saas/acceptance/p3-upstream-sync-ci-30897083447.json",
    "saas/acceptance/p4-scheduling-ci-30901594129.json",
    "saas/acceptance/p4-image-candidate-ci-30901594130.json",
    "saas/acceptance/p4-containment-egress-ci-30921247156.json",
    "saas/acceptance/p4-isolation-preview-ci-30918608868.json",
    "saas/acceptance/p4-physical-worktree-ci-30910478415.json",
    "saas/acceptance/p4-preview-gateway-authority-ci-30955223169.json",
    "saas/acceptance/p4-preview-gateway-process-ci-30964370004.json",
    "saas/acceptance/p4-preview-gateway-control-ci-30967154951.json",
    "saas/acceptance/p4-preview-gateway-runtime-ci-30959947571.json",
    "saas/acceptance/p4-preview-relay-ci-30951270461.json",
    "saas/acceptance/p4-preview-tunnel-ci-30923776172.json",
    "saas/acceptance/p4-preview-uds-ci-30926375395.json",
    "saas/acceptance/p4-preview-supervisor-ci-30937413470.json",
    "saas/acceptance/p4-runner-certificate-lifecycle-ci-30942353100.json",
    "saas/acceptance/p4-runner-tunnel-placement-ci-30948364396.json",
    "saas/acceptance/p4-secret-broker-mtls-ci-30929785430.json",
    "saas/acceptance/p4-upstream-sync-ci-30932712224.json",
    "saas/acceptance/p4-worktree-ci-30906291765.json",
    "saas/acceptance/p5-image-supply-chain-contract-ci-30994862629.json",
    "saas/acceptance/p5-image-candidate-ci-30978680569.json",
    "saas/acceptance/p5-logical-restore-contract-ci-30986200469.json",
    "saas/acceptance/p5-recovery-evidence-contract-ci-30983318630.json",
    "saas/acceptance/p5-slo-capacity-contract-ci-30991532016.json",
    "saas/acceptance/p5-tenant-deletion-contract-ci-30988807799.json",
    "saas/acceptance/p5-webhook-delivery-ci-30980110086.json",
    "saas/acceptance/p6-api-service-account-ci-31002035206.json",
    "saas/acceptance/p6-enterprise-approval-admin-console-ci-31030826038.json",
    "saas/acceptance/p6-enterprise-approval-stale-read-ci-31032344986.json",
    "saas/acceptance/p6-tenant-members-admin-console-ci-31042515162.json",
    "saas/acceptance/p6-tenant-members-image-candidate-ci-31043457794.json",
    "saas/acceptance/p6-billing-ledger-ci-31055362434.json",
    "saas/acceptance/p6-machine-metering-ci-31063360786.json",
    "saas/acceptance/p6-machine-metering-image-candidate-ci-31064837882.json",
    "saas/acceptance/p6-provider-runtime-metering-ci-31068082417.json",
    "saas/acceptance/p6-enterprise-access-preflight-ci-31025362985.json",
    "saas/acceptance/p6-enterprise-access-lifecycle-ci-31016011969.json",
    "saas/acceptance/p6-enterprise-group-custom-role-ci-31008792059.json",
    "saas/acceptance/p6-upstream-sync-ci-31011047850.json",
    "saas/acceptance/p6-upstream-sync-ci-31019511803.json",
    "saas/acceptance/p6-upstream-sync-ci-31236956326.json",
    "saas/acceptance/p6-upstream-sync-image-candidate-ci-31236978641.json",
    "saas/admin_ui/project_admin.css",
    "saas/admin_ui/project_admin.html",
    "saas/admin_ui/project_admin.js",
    "saas/admin_ui/platform_admin.css",
    "saas/admin_ui/platform_admin.html",
    "saas/admin_ui/platform_admin.js",
    "saas/admin_ui/platform_privacy.css",
    "saas/admin_ui/platform_privacy.js",
    "saas/onboarding_ui/onboarding.css",
    "saas/onboarding_ui/onboarding.html",
    "saas/onboarding_ui/onboarding.js",
    "saas/upstream-baseline.json",
    "saas/compatibility/store_adapter.py",
    "saas/control_plane/api_credential_models.py",
    "saas/control_plane/api_credentials.py",
    "saas/control_plane/api_http.py",
    "saas/control_plane/billing.py",
    "saas/control_plane/billing_http.py",
    "saas/control_plane/billing_metering.py",
    "saas/control_plane/billing_models.py",
    "saas/control_plane/authorization.py",
    "saas/control_plane/binding_saga.py",
    "saas/control_plane/bindings.py",
    "saas/control_plane/certificate_models.py",
    "saas/control_plane/certificates.py",
    "saas/control_plane/context_snapshot.py",
    "saas/control_plane/alembic.ini",
    "saas/control_plane/db_models.py",
    "saas/control_plane/execution_models.py",
    "saas/control_plane/execution.py",
    "saas/control_plane/enterprise_access.py",
    "saas/control_plane/enterprise_identity.py",
    "saas/control_plane/enterprise_identity_models.py",
    "saas/control_plane/enterprise_scim_http.py",
    "saas/control_plane/enterprise_http.py",
    "saas/control_plane/enterprise_models.py",
    "saas/control_plane/governance.py",
    "saas/control_plane/gateway_models.py",
    "saas/control_plane/gateways.py",
    "saas/control_plane/http_auth.py",
    "saas/control_plane/idempotency.py",
    "saas/control_plane/identity.py",
    "saas/control_plane/isolation.py",
    "saas/control_plane/isolation_models.py",
    "saas/control_plane/lifecycle.py",
    "saas/control_plane/member_admin.py",
    "saas/control_plane/member_http.py",
    "saas/control_plane/migrations/env.py",
    "saas/control_plane/migrations/script.py.mako",
    "saas/control_plane/migrations/versions/p1a000000001_identity_tenant_placement.py",
    "saas/control_plane/migrations/versions/p1a000000002_identity_lifecycle.py",
    "saas/control_plane/migrations/versions/p1a000000003_auth_governance_outbox.py",
    "saas/control_plane/migrations/versions/p2a000000001_postgresql_rls.py",
    "saas/control_plane/migrations/versions/p2a000000002_project_authorization.py",
    "saas/control_plane/migrations/versions/p2a000000003_binding_saga.py",
    "saas/control_plane/migrations/versions/p2a000000004_force_control_plane_rls.py",
    "saas/control_plane/migrations/versions/p2a000000005_oidc_identity_conflicts.py",
    "saas/control_plane/migrations/versions/p2a000000006_context_shell_actor_rls.py",
    "saas/control_plane/migrations/versions/p2a000000007_runtime_placement_platform_write.py",
    "saas/control_plane/migrations/versions/p3a000000001_execution_authority.py",
    "saas/control_plane/migrations/versions/p4a000000001_runner_scheduling.py",
    "saas/control_plane/migrations/versions/p4b000000001_changeset_worktrees.py",
    "saas/control_plane/migrations/versions/p4c000000001_isolation_secret_preview.py",
    "saas/control_plane/migrations/versions/p4d000000001_runner_certificate_lifecycle.py",
    "saas/control_plane/migrations/versions/p4e000000001_runner_tunnel_placement.py",
    "saas/control_plane/migrations/versions/p4f000000001_preview_gateway_authority.py",
    "saas/control_plane/migrations/versions/p4g000000001_preview_gateway_runtime_lifecycle.py",
    "saas/control_plane/migrations/versions/p5a000000001_webhook_delivery.py",
    "saas/control_plane/migrations/versions/p6a000000001_api_service_accounts.py",
    "saas/control_plane/migrations/versions/p6a000000002_enterprise_groups_roles.py",
    "saas/control_plane/migrations/versions/p6a000000003_enterprise_access_lifecycle.py",
    "saas/control_plane/migrations/versions/p6a000000004_enterprise_access_preflights.py",
    "saas/control_plane/migrations/versions/p6a000000005_enterprise_approval_inbox.py",
    "saas/control_plane/migrations/versions/p6a000000006_tenant_member_directory.py",
    "saas/control_plane/migrations/versions/p6a000000007_invitation_acceptance_rls.py",
    "saas/control_plane/migrations/versions/p6a000000008_billing_authority.py",
    "saas/control_plane/migrations/versions/p6a000000009_machine_metering.py",
    "saas/control_plane/migrations/versions/pc1a00000001_platform_security_foundation.py",
    "saas/control_plane/migrations/versions/pc2a00000001_platform_user_tenant_lifecycle.py",
    "saas/control_plane/migrations/versions/pc2b00000001_identity_conflict_platform_review.py",
    "saas/control_plane/migrations/versions/pc3a00000001_platform_governed_access.py",
    "saas/control_plane/migrations/versions/pc5a00000001_enterprise_scim_convergence.py",
    "saas/control_plane/migrations/versions/pc5a00000002_scim_bulk_receipts.py",
    "saas/control_plane/migrations/versions/pc5a00000003_scim_credential_overlap.py",
    "saas/control_plane/migrations/versions/pc5a00000004_scim_schema_extensions.py",
    "saas/control_plane/migrations/versions/pc5a00000005_scim_token_match_helper.py",
    "saas/control_plane/migrations/versions/pc5b00000001_privacy_deletion_foundation.py",
    "saas/control_plane/migrations/versions/pc5b00000002_privacy_auditor_read.py",
    "saas/control_plane/migrations/versions/pc5b00000003_privacy_execution_authority.py",
    "saas/control_plane/migrations/versions/pc5c00000001_notification_approval_operations.py",
    "saas/control_plane/migrations/versions/pc5c00000002_notification_security_followup.py",
    "saas/control_plane/migrations/versions/p0s000000001_self_service_onboarding.py",
    "saas/control_plane/migrations/versions/p6b000000001_billing_period_close.py",
    "saas/control_plane/platform_lifecycle.py",
    "saas/control_plane/platform_governed_access.py",
    "saas/control_plane/platform_governed_models.py",
    "saas/control_plane/platform_support_http.py",
    "saas/control_plane/outbox.py",
    "saas/control_plane/onboarding.py",
    "saas/control_plane/onboarding_http.py",
    "saas/control_plane/onboarding_models.py",
    "saas/control_plane/onboarding_status.py",
    "saas/control_plane/runtime_provider.py",
    "saas/control_plane/runtime_provider_journal.py",
    "saas/control_plane/placement_models.py",
    "saas/control_plane/placements.py",
    "saas/control_plane/permissions.py",
    "saas/control_plane/approval_operations.py",
    "saas/control_plane/approval_scheduler.py",
    "saas/control_plane/approval_source_adapters.py",
    "saas/control_plane/approval_source_projection.py",
    "saas/control_plane/notification_delivery.py",
    "saas/control_plane/notification_events.py",
    "saas/control_plane/notification_http.py",
    "saas/control_plane/notification_models.py",
    "saas/control_plane/notification_templates.py",
    "saas/control_plane/platform_notification_http.py",
    "saas/control_plane/platform_http.py",
    "saas/control_plane/platform_models.py",
    "saas/control_plane/platform_security.py",
    "saas/control_plane/privacy_lifecycle.py",
    "saas/control_plane/privacy_models.py",
    "saas/control_plane/postgresql_database.psql",
    "saas/control_plane/postgresql_database.sql",
    "saas/control_plane/postgresql_principals.psql",
    "saas/control_plane/postgresql_principals.sql",
    "saas/control_plane/postgresql_runner_agent_cluster.psql",
    "saas/control_plane/postgresql_runner_agent_cluster.sql",
    "saas/control_plane/postgresql_roles.sql",
    "saas/control_plane/postgresql_roles.psql",
    "saas/control_plane/project_http.py",
    "saas/control_plane/projects.py",
    "saas/control_plane/removal_impact.py",
    "saas/control_plane/resolver.py",
    "saas/control_plane/rls.py",
    "saas/control_plane/rls_inventory.py",
    "saas/control_plane/scheduling.py",
    "saas/control_plane/run_dispatch_projection.py",
    "saas/control_plane/scheduling_models.py",
    "saas/control_plane/webhook_models.py",
    "saas/control_plane/webhooks.py",
    "saas/control_plane/worktree_models.py",
    "saas/control_plane/worktrees.py",
    "saas/deployment/__init__.py",
    "saas/deployment/server/__init__.py",
    "saas/deployment/server/README.md",
    "saas/deployment/server/kubernetes.artifact-admission.yaml",
    "saas/deployment/server/kubernetes.migration.yaml",
    "saas/deployment/server/kubernetes.network-policy.yaml",
    "saas/deployment/server/kubernetes.production.yaml",
    "saas/deployment/data/__init__.py",
    "saas/deployment/data/README.md",
    "saas/deployment/data/restore-drill-evidence.schema.json",
    "saas/deployment/preview_gateway/README.md",
    "saas/deployment/preview_gateway/config.example.json",
    "saas/deployment/preview_gateway/kubernetes.yaml",
    "saas/deployment/preview_gateway/omnigent-saas-preview-gateway@.service",
    "saas/outbox_worker.py",
    "saas/n1_outbox_admission.py",
    "saas/onboarding_email.py",
    "saas/onboarding_composition.py",
    "saas/control_plane/postgresql_role_authority.py",
    "saas/control_plane/onboarding_workflow.py",
    "saas/control_plane/migrations/versions/p0s000000002_onboarding_vertical_chain.py",
    "saas/control_plane/migrations/versions/p0s000000003_outbox_quarantine.py",
    "saas/control_plane/migrations/versions/p0s000000004_runtime_provider_journal.py",
    "saas/control_plane/migrations/versions/p0s000000005_registration_rate_limits.py",
    "saas/control_plane/migrations/versions/p0s000000006_registration_network_rate_limits.py",
    "saas/control_plane/migrations/versions/p0s000000007_registration_subject_lock_budget.py",
    "saas/control_plane/migrations/versions/p0s000000008_dispatch_profile_binding.py",
    "saas/control_plane/migrations/versions/p0s000000009_preview_execution_sessions.py",
    "saas/control_plane/migrations/versions/p0s000000010_runner_agent_database_authority.py",
    "saas/control_plane/migrations/versions/p0s000000011_notification_policy_role_scope.py",
    "saas/control_plane/preview_execution.py",
    "saas/control_plane/preview_models.py",
    "saas/control_plane/preview_sessions.py",
    "saas/control_plane/preview_tunnel_registration.py",
    "saas/control_plane/runner_execution_spec.py",
    "saas/notification_bootstrap.py",
    "saas/notification_runtime.py",
    "saas/notification_worker.py",
    "saas/privacy_worker.py",
    "saas/preview_gateway.py",
    "saas/preview_gateway_control_transport.py",
    "saas/preview_gateway_process.py",
    "saas/preview_gateway_runtime.py",
    "saas/preview_relay_transport.py",
    "saas/preview_tunnel.py",
    "saas/runtime_rls/__init__.py",
    "saas/runtime_rls/installer.py",
    "saas/runtime_rls/postgresql_roles.sql",
    "saas/runtime_rls/postgresql_roles.psql",
    "saas/runner_adapter/__init__.py",
    "saas/runner_adapter/containment.py",
    "saas/runner_adapter/isolation.py",
    "saas/runner_adapter/managed_entry.py",
    "saas/runner_adapter/metering.py",
    "saas/runner_adapter/preview_supervisor.py",
    "saas/runner_adapter/process_policy.py",
    "saas/runner_adapter/static_web_preview.py",
    "saas/runner_adapter/worktrees.py",
    "saas/secret_broker_transport.py",
    "saas/production/baseline.json",
    "saas/production/adr-approval-policy.json",
    "saas/production/adr-approval-authorities.json",
    "saas/production/adr-approval-candidate.json",
    "saas/production/adr-approvals/README.md",
    "saas/production/adr-approvals/omnigent-saas-upstream-sync-3369b36c-2026-08-31-2500a820699ccb24.json",
    "saas/production/adr-approvals/omnigent-saas-p0-sole-owner-waiver-2026-08-09-59c80f30abe891bb.json",
    "saas/production/adrs/README.md",
    "saas/production/adrs/ADR-001-postgresql-topology-and-transactions.md",
    "saas/production/adrs/ADR-002-runtime-placement-and-migration.md",
    "saas/production/adrs/ADR-003-authorization-snapshot-and-degradation.md",
    "saas/production/adrs/ADR-004-runner-isolation-and-responsibility.md",
    "saas/production/adrs/ADR-005-sandbox-network-secret-supply-chain.md",
    "saas/production/adrs/ADR-006-slo-data-class-recovery.md",
    "saas/production/adrs/ADR-007-metering-ledgers-and-quota.md",
    "saas/production/adrs/ADR-008-api-webhook-connector-ssrf.md",
    "saas/production/adrs/ADR-009-single-region-production-boundary.md",
    "saas/production/adrs/ADR-010-identity-and-management-web-security.md",
    "saas/production/adrs/ADR-011-feature-flag-and-configuration.md",
    "saas/production/deletion.py",
    "saas/production/deletion-policy.json",
    "saas/production/notification-template-catalog.json",
    "saas/production/notification-template-manifest.json",
    "saas/production/deployment.py",
    "saas/production/deployment-policy.json",
    "saas/production/admission.py",
    "saas/production/evidence-admission-policy.json",
    "saas/production/evidence-admission-keys.json",
    "saas/production/evidence-admission-receipts/README.md",
    "saas/production/business.py",
    "saas/production/commercial-policy.json",
    "saas/production/enterprise-policy.json",
    "saas/production/scim-compliance-matrix.json",
    "saas/production/readiness.py",
    "saas/production/artifact_admission.py",
    "saas/production/artifact_store.py",
    "saas/production/postgresql_migration.py",
    "saas/production/server.py",
    "saas/production/server_config.py",
    "saas/production/service_bindings.py",
    "saas/production/worker.py",
    "saas/production/runner_control.py",
    "saas/production/runner_database_fleet.py",
    "saas/production/beta_postgresql_data_plane.py",
    "saas/production/runner_agent.py",
    "saas/production/repository_mirror.py",
    "saas/production/runner_executor.py",
    "saas/production/runner_readiness.py",
    "saas/production/preview_control.py",
    "saas/production/preview_edge.py",
    "saas/production/preview_execution.py",
    "saas/production/preview_owner.py",
    "saas/production/preview_readiness.py",
    "saas/production/preview_relay.py",
    "saas/production/preview_runner_tunnel.py",
    "saas/production/upstream-sync-policy.json",
    "saas/production/slo_capacity.py",
    "saas/production/slo-capacity-policy.json",
    "saas/production/recovery.py",
    "saas/production/recovery-policy.json",
    "saas/production/postgresql_restore.py",
    "saas/production/runbooks/backup-restore.md",
    "saas/production/runbooks/api-credentials.md",
    "saas/production/runbooks/billing-ledger.md",
    "saas/production/runbooks/enterprise-access-lifecycle.md",
    "saas/production/runbooks/scim-idp-e2e.md",
    "saas/production/runbooks/tenant-members.md",
    "saas/production/runbooks/control-plane-degradation.md",
    "saas/production/runbooks/image-release.md",
    "saas/production/runbooks/incident-response.md",
    "saas/production/runbooks/platform-security.md",
    "saas/production/runbooks/tenant-deletion.md",
    "saas/production/runbooks/production-deployment.md",
    "saas/production/runbooks/production-admission.md",
    "saas/production/runbooks/slo-capacity.md",
    "saas/scripts/check_deployment_readiness.py",
    "saas/scripts/check_worker_health.py",
    "saas/scripts/check_runner_control_readiness.py",
    "saas/scripts/finalize_artifact_receipt_revision.py",
    "saas/scripts/render_kubernetes_namespace.py",
    "saas/scripts/render_kubernetes_release.py",
    "saas/scripts/check_deletion_readiness.py",
    "saas/scripts/check_commercial_readiness.py",
    "saas/scripts/check_enterprise_readiness.py",
    "saas/scripts/check_evidence_admission.py",
    "saas/scripts/check_production_readiness.py",
    "saas/scripts/check_adr_approvals.py",
    "saas/scripts/finalize_adr_approval.py",
    "saas/scripts/check_image_supply_chain.py",
    "saas/scripts/check_production_baseline.py",
    "saas/scripts/check_recovery_readiness.py",
    "saas/scripts/check_slo_capacity_readiness.py",
    "saas/scripts/run_production_admission.py",
    "saas/scripts/run_postgresql_migration.py",
    "saas/scripts/provision_runner_repositories.py",
    "saas/scripts/stage_runner_database_fleet.py",
    "saas/scripts/verify_runner_database_fleet.py",
    "saas/scripts/promote_runner_database_fleet.py",
    "saas/scripts/render_beta_postgresql_data_plane.py",
    "saas/scripts/run_postgresql_restore_contract.py",
    "saas/scripts/compare_oci_rebuilds.py",
    "saas/supply_chain/release-policy.json",
)


def find_missing_paths(names: Collection[str]) -> list[str]:
    """Return required SaaS artifacts absent from a wheel member list."""

    return sorted(path for path in REQUIRED_WHEEL_PATHS if path not in names)


def _select_wheel(path: Path) -> Path:
    if path.is_file() and path.suffix == ".whl":
        return path
    wheels = sorted(path.glob("omnigent-*.whl")) if path.is_dir() else []
    if len(wheels) != 1:
        raise ValueError("expected exactly one Omnigent wheel")
    return wheels[0]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("wheel", help="wheel file or directory containing one wheel")
    args = parser.parse_args()

    try:
        wheel = _select_wheel(Path(args.wheel))
        with zipfile.ZipFile(wheel) as archive:
            missing = find_missing_paths(set(archive.namelist()))
    except (OSError, ValueError, zipfile.BadZipFile) as error:
        sys.stderr.write(f"wheel verification failed: {error}\n")
        return 1

    if missing:
        sys.stderr.write("wheel is missing SaaS artifacts:\n")
        sys.stderr.write("\n".join(missing) + "\n")
        return 1
    sys.stdout.write(f"wheel contains {len(REQUIRED_WHEEL_PATHS)} required SaaS artifacts\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
