"""SaaS-owned identity, tenancy, and runtime-placement control plane."""

from saas.control_plane.db_models import (
    AuthSessionRecord,
    ControlPlaneOutboxEvent,
    GlobalUser,
    IdentityConnection,
    MemberRemovalPreflightRecord,
    MembershipInvitation,
    OwnershipTransferRecord,
    PasswordCredential,
    RuntimeIdentityAliasRecord,
    RuntimePartitionRecord,
    RuntimePlacementRecord,
    RuntimeResourceBindingRecord,
    SaasBase,
    Space,
    SpaceMembership,
    Tenant,
    TenantMembership,
)
from saas.control_plane.governance import (
    MemberRemoved,
    MembershipGovernanceService,
    OwnershipTransferred,
    RemovalImpact,
    RemovalImpactProvider,
    RemovalPreflight,
    UnavailableRemovalImpactProvider,
)
from saas.control_plane.http_auth import (
    SaasAuthContextMiddleware,
    SaasAuthProvider,
    SaasCookieConfig,
    SaasHttpIntegration,
    create_saas_auth_router,
    create_saas_http_integration,
)
from saas.control_plane.identity import (
    IdentityManagementService,
    PasswordChanged,
    PasswordCredentialService,
    VerifiedIdentityAssertion,
)
from saas.control_plane.lifecycle import (
    InvitationAccepted,
    InvitationCreated,
    IssuedAuthSession,
    LifecycleError,
    MembershipChanged,
    MembershipLifecycleService,
    ValidatedAuthSession,
    normalize_email,
)
from saas.control_plane.outbox import DispatchResult, OutboxDispatcher, OutboxPublisher
from saas.control_plane.resolver import (
    ControlPlaneResolutionError,
    RuntimeCompatibilityPolicy,
    SqlAlchemyContextResolver,
    load_runtime_compatibility_policy,
)
from saas.control_plane.rls import RlsContext, apply_rls_context

__all__ = [
    "AuthSessionRecord",
    "ControlPlaneOutboxEvent",
    "ControlPlaneResolutionError",
    "DispatchResult",
    "GlobalUser",
    "IdentityConnection",
    "IdentityManagementService",
    "InvitationAccepted",
    "InvitationCreated",
    "IssuedAuthSession",
    "LifecycleError",
    "MemberRemovalPreflightRecord",
    "MemberRemoved",
    "MembershipChanged",
    "MembershipGovernanceService",
    "MembershipInvitation",
    "MembershipLifecycleService",
    "OutboxDispatcher",
    "OutboxPublisher",
    "OwnershipTransferRecord",
    "OwnershipTransferred",
    "PasswordChanged",
    "PasswordCredential",
    "PasswordCredentialService",
    "RemovalImpact",
    "RemovalImpactProvider",
    "RemovalPreflight",
    "RlsContext",
    "RuntimeCompatibilityPolicy",
    "RuntimeIdentityAliasRecord",
    "RuntimePartitionRecord",
    "RuntimePlacementRecord",
    "RuntimeResourceBindingRecord",
    "SaasAuthContextMiddleware",
    "SaasAuthProvider",
    "SaasBase",
    "SaasCookieConfig",
    "SaasHttpIntegration",
    "Space",
    "SpaceMembership",
    "SqlAlchemyContextResolver",
    "Tenant",
    "TenantMembership",
    "UnavailableRemovalImpactProvider",
    "ValidatedAuthSession",
    "VerifiedIdentityAssertion",
    "apply_rls_context",
    "create_saas_auth_router",
    "create_saas_http_integration",
    "load_runtime_compatibility_policy",
    "normalize_email",
]
