"""SaaS-owned identity, tenancy, and runtime-placement control plane."""

from saas.control_plane.authorization import (
    AuthorizationDecision,
    AuthorizationSource,
    ProjectAuthorizationError,
    ProjectAuthorizer,
)
from saas.control_plane.binding_saga import (
    ProvisioningTarget,
    RuntimeBindingSagaResult,
    RuntimeBindingSagaService,
    RuntimeProvisioningError,
    RuntimeResourceProvisioner,
)
from saas.control_plane.bindings import RuntimeBindingChanged, RuntimeBindingService
from saas.control_plane.db_models import (
    AuthorizationDecisionRecord,
    AuthSessionRecord,
    ControlPlaneOutboxEvent,
    GlobalUser,
    IdentityConnection,
    MemberRemovalPreflightRecord,
    MembershipInvitation,
    OwnershipTransferRecord,
    PasswordCredential,
    ProjectMembershipRecord,
    ProjectRecord,
    ResourceGrantRecord,
    RuntimeBindingSagaRecord,
    RuntimeIdentityAliasRecord,
    RuntimePartitionRecord,
    RuntimePlacementRecord,
    RuntimeResourceBindingRecord,
    SaasBase,
    Space,
    SpaceMembership,
    Tenant,
    TenantMembership,
)
from saas.control_plane.governance import (
    MemberRemoved,
    MembershipGovernanceService,
    OwnershipTransferred,
    RemovalImpact,
    RemovalImpactProvider,
    RemovalPreflight,
    UnavailableRemovalImpactProvider,
)
from saas.control_plane.http_auth import (
    SaasAuthContextMiddleware,
    SaasAuthProvider,
    SaasCookieConfig,
    SaasHttpIntegration,
    create_saas_auth_router,
    create_saas_http_integration,
)
from saas.control_plane.identity import (
    IdentityManagementService,
    PasswordChanged,
    PasswordCredentialService,
    VerifiedIdentityAssertion,
)
from saas.control_plane.lifecycle import (
    InvitationAccepted,
    InvitationCreated,
    IssuedAuthSession,
    LifecycleError,
    MembershipChanged,
    MembershipLifecycleService,
    ValidatedAuthSession,
    normalize_email,
)
from saas.control_plane.outbox import DispatchResult, OutboxDispatcher, OutboxPublisher
from saas.control_plane.permissions import (
    PERMISSION_CATALOG,
    POLICY_VERSION,
    PROJECT_ROLE_PERMISSIONS,
    RESOURCE_ROLE_PERMISSIONS,
    SPACE_ROLE_PERMISSIONS,
    TENANT_ROLE_PERMISSIONS,
    PermissionDefinition,
    PermissionRisk,
    PermissionScope,
    permission_catalog_payload,
)
from saas.control_plane.project_http import (
    PROJECT_ADMIN_ROUTE_PERMISSIONS,
    create_project_admin_router,
    validate_project_admin_route_permissions,
)
from saas.control_plane.projects import (
    ProjectAdministrationService,
    ProjectChanged,
    ProjectCreated,
    ProjectMetadata,
    ScopedGrantChanged,
)
from saas.control_plane.removal_impact import ProjectRemovalImpactProvider
from saas.control_plane.resolver import (
    ControlPlaneResolutionError,
    RuntimeCompatibilityPolicy,
    SqlAlchemyContextResolver,
    load_runtime_compatibility_policy,
)
from saas.control_plane.rls import RlsContext, apply_rls_context

__all__ = [
    "PERMISSION_CATALOG",
    "POLICY_VERSION",
    "PROJECT_ADMIN_ROUTE_PERMISSIONS",
    "PROJECT_ROLE_PERMISSIONS",
    "RESOURCE_ROLE_PERMISSIONS",
    "SPACE_ROLE_PERMISSIONS",
    "TENANT_ROLE_PERMISSIONS",
    "AuthSessionRecord",
    "AuthorizationDecision",
    "AuthorizationDecisionRecord",
    "AuthorizationSource",
    "ControlPlaneOutboxEvent",
    "ControlPlaneResolutionError",
    "DispatchResult",
    "GlobalUser",
    "IdentityConnection",
    "IdentityManagementService",
    "InvitationAccepted",
    "InvitationCreated",
    "IssuedAuthSession",
    "LifecycleError",
    "MemberRemovalPreflightRecord",
    "MemberRemoved",
    "MembershipChanged",
    "MembershipGovernanceService",
    "MembershipInvitation",
    "MembershipLifecycleService",
    "OutboxDispatcher",
    "OutboxPublisher",
    "OwnershipTransferRecord",
    "OwnershipTransferred",
    "PasswordChanged",
    "PasswordCredential",
    "PasswordCredentialService",
    "PermissionDefinition",
    "PermissionRisk",
    "PermissionScope",
    "ProjectAdministrationService",
    "ProjectAuthorizationError",
    "ProjectAuthorizer",
    "ProjectChanged",
    "ProjectCreated",
    "ProjectMembershipRecord",
    "ProjectMetadata",
    "ProjectRecord",
    "ProjectRemovalImpactProvider",
    "ProvisioningTarget",
    "RemovalImpact",
    "RemovalImpactProvider",
    "RemovalPreflight",
    "ResourceGrantRecord",
    "RlsContext",
    "RuntimeBindingChanged",
    "RuntimeBindingSagaRecord",
    "RuntimeBindingSagaResult",
    "RuntimeBindingSagaService",
    "RuntimeBindingService",
    "RuntimeCompatibilityPolicy",
    "RuntimeIdentityAliasRecord",
    "RuntimePartitionRecord",
    "RuntimePlacementRecord",
    "RuntimeProvisioningError",
    "RuntimeResourceBindingRecord",
    "RuntimeResourceProvisioner",
    "SaasAuthContextMiddleware",
    "SaasAuthProvider",
    "SaasBase",
    "SaasCookieConfig",
    "SaasHttpIntegration",
    "ScopedGrantChanged",
    "Space",
    "SpaceMembership",
    "SqlAlchemyContextResolver",
    "Tenant",
    "TenantMembership",
    "UnavailableRemovalImpactProvider",
    "ValidatedAuthSession",
    "VerifiedIdentityAssertion",
    "apply_rls_context",
    "create_project_admin_router",
    "create_saas_auth_router",
    "create_saas_http_integration",
    "load_runtime_compatibility_policy",
    "normalize_email",
    "permission_catalog_payload",
    "validate_project_admin_route_permissions",
]
