"""SaaS-owned identity, tenancy, and runtime-placement control plane."""

from saas.control_plane.db_models import (
    AuthSessionRecord,
    ControlPlaneOutboxEvent,
    GlobalUser,
    IdentityConnection,
    MembershipInvitation,
    RuntimeIdentityAliasRecord,
    RuntimePartitionRecord,
    RuntimePlacementRecord,
    RuntimeResourceBindingRecord,
    SaasBase,
    Space,
    SpaceMembership,
    Tenant,
    TenantMembership,
)
from saas.control_plane.lifecycle import (
    InvitationAccepted,
    InvitationCreated,
    IssuedAuthSession,
    LifecycleError,
    MembershipChanged,
    MembershipLifecycleService,
    ValidatedAuthSession,
    normalize_email,
)
from saas.control_plane.resolver import (
    ControlPlaneResolutionError,
    RuntimeCompatibilityPolicy,
    SqlAlchemyContextResolver,
    load_runtime_compatibility_policy,
)

__all__ = [
    "AuthSessionRecord",
    "ControlPlaneOutboxEvent",
    "ControlPlaneResolutionError",
    "GlobalUser",
    "IdentityConnection",
    "InvitationAccepted",
    "InvitationCreated",
    "IssuedAuthSession",
    "LifecycleError",
    "MembershipChanged",
    "MembershipInvitation",
    "MembershipLifecycleService",
    "RuntimeCompatibilityPolicy",
    "RuntimeIdentityAliasRecord",
    "RuntimePartitionRecord",
    "RuntimePlacementRecord",
    "RuntimeResourceBindingRecord",
    "SaasBase",
    "Space",
    "SpaceMembership",
    "SqlAlchemyContextResolver",
    "Tenant",
    "TenantMembership",
    "ValidatedAuthSession",
    "load_runtime_compatibility_policy",
    "normalize_email",
]
